### ISSUE TITLE
Support for starting the RPC

### ISSUE THREAD

**Issue by dginovker** [monero-ecosystem/monero-python#46]
Right now, creating a wallet requires the RPC to already be running on a port. Could support for starting the RPC with parameters be added?

Also, thank you so much for the documentation! It was very well written :+1:

**Comment by emesik** [comment]
There's already [a short instruction in the docs](https://monero-python.readthedocs.io/en/latest/quickstart.html#start-the-rpc-server). What other kind of support could be helpful there?

**Comment by dginovker** [comment]
I'd like to be able to call that command from Python - without going through exec.

**Comment by emesik** [comment]
The `monero-wallet-rpc` is a standalone executable for a reason. Everybody may launch it in whatever way they please; most likely under service supervisor like `systemd`, or manually. There's no need to wrap it in additional Python code because most users won't launch it via Python at all.

You may check my other project: [wallet pool manager](https://github.com/emesik/monerowalletpool) for a solution similar to what you're proposing here, although in reality it's much more complicated than a single line of code. Mostly because of the time spent by wallet on syncing the blockchain before RPC calls are allowed at all.
