### ISSUE TITLE
new_address() fails for OfflineWallet

### ISSUE THREAD

**Issue by mrx23dot** [monero-ecosystem/monero-python#95]
Why can't I generate random **new_address()** subaddresses for OfflineWallet?
For random address generation collision is less likely.

```
    return self._backend.new_address(account=self.index, label=label)
  File "C:\Python36\lib\site-packages\monero\backends\offline.py", line 49, in new_address
    raise WalletIsOffline()
monero.backends.offline.WalletIsOffline
```

Currently it requires open wallet file in RPC. 
Offline example uses get_address(major, minor)
https://monero-python.readthedocs.io/en/latest/backends.html

**Comment by emesik** [comment]
First of all, `new_address()` is not a random but sequential address generator. It appends a new address to the list of already generated ones in the wallet, increasing the *minor* index. Since the `OfflineWallet` doesn't connect to any real wallet, there's no such list.

Please keep in mind that every wallet software checks for payments only those **addresses that have been generated already** (and sometimes a handful of future ones, in sequential order).

You may, of course, implement your own backend that manages the list of subaddresses and implements `new_address()`. Remember to keep the list in persistent storage, or every time you restart the program, it would generate addresses starting again from `minor=1`.

**Comment by mrx23dot** [comment]
Thank you!
